name: "SWD Deployment Notes"

on:
    push:
        branches:
        - main
            
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with: 
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - name: Install dependencies
      run: npm install
    - name: Build file
      run: npm run build
    
    - name: Deploy production to netlify
      uses: South-Paw/action-netlify-deploy@1.20
      with:
        github-token: ${{ secrets.GITHUB-TOKEN }}
        netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
        build-dir: './build'
        comment-on-commit: false
      
      
      


  
